### ISSUE TITLE
Status response: 403 Forbidden (SKILL_DISABLED_EXCEPTION)

### ISSUE THREAD

**Issue by Thundras** [sweharris/Alexa-Smart-Home-VirtualButtons#6] opened 2023-11-11 18:41 UTC
Hi ,
I have successfully set up the skill and connected it to Alexa. I can add buttons that are also successfully dicovered by Alexa. Even if I change the state of a button, this is displayed correctly in the alexa app. 

However, when I change the status, my routine for the sensor is not triggered. Instead, I see an error 403 (SKILL_DISABLED_EXCEPTION) in the log after "Pushing a notification to Alexa". 
I have also already tried to disconnect and reconnect the skill, but there are no errors. 

Does anyone have any idea what is wrong?

Here is the complete log for the state change:

<html>
<body>

START RequestId: 189c76d4-9038-4137-aded-5ca8a75904a9 Version: $LATEST
--
2023/11/11 14:38:17 Handler started
2023/11/11 14:38:17 Incoming data:  {     "version": "2.0",     "routeKey": "$default",     "rawPath": "/",     "rawQueryString": "",     "headers": {         "authorization": "zJ9z8us",         "content-length": "50",         "x-amzn-tls-cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256",         "x-amzn-tls-version": "TLSv1.2",         "x-amzn-trace-id": "Root=1-654f91d9-1403f67622748cb23b2c13e0",         "x-forwarded-proto": "https",         "host": "7bdzfnjyeyyzwh6kjnefvz3kqy0leked.lambda-url.eu-west-1.on.aws",         "x-forwarded-port": "443",         "content-type": "application/json; charset=utf-8",         "x-forwarded-for": "94.31.83.140",         "accept": "application/json"     },     "requestContext": {         "accountId": "anonymous",         "apiId": "7bdzfnjyeyyzwh6kjnefvz3kqy0leked",         "domainName": "7bdzfnjyeyyzwh6kjnefvz3kqy0leked.lambda-url.eu-west-1.on.aws",         "domainPrefix": "7bdzfnjyeyyzwh6kjnefvz3kqy0leked",         "http": {             "method": "POST",             "path": "/",             "protocol": "HTTP/1.1",             "sourceIp": "94.31.83.140",             "userAgent": null         },         "requestId": "189c76d4-9038-4137-aded-5ca8a75904a9",         "routeKey": "$default",         "stage": "$default",         "time": "11/Nov/2023:14:38:17 +0000",         "timeEpoch": 1699713497507     },     "body": "{\"command\":\"setstate\", \"param1\":\"1\", \"param2\":\"0\"}",     "isBase64Encoded": false }
2023/11/11 14:38:17 API call
2023/11/11 14:38:17 Body is: {     "command": "setstate",     "param1": "1",     "param2": "0" }
2023/11/11 14:38:17 Pushing a notification to Alexa
2023/11/11 14:38:17 No refresh needed
2023/11/11 14:38:17 {     "event": {         "header": {             "namespace": "Alexa",             "name": "ChangeReport",             "messageId": "89dbd8b1-d775-4577-8540-2f0993e33837",             "payloadVersion": "3"         },         "endpoint": {             "scope": {                 "type": "BearerToken",                 "token": "Atza\|IwEBIBCzjAbEfMPNvkI728rhuFtgPtb6keOAMWwsgBRlupXLNJ4mL_Fk0-YIT_yfIoPvlUXLWRZLoqcg7KLBrQpwvMKi63RjlqEP5_ghY4nJPoWSkMmFzwM98Mx1iIC6BfNWHjLtaafwmBpRKNLAL-sa_Yr5isbVtwuOFq8J_m3OCRaSPdSVTeTbDCqleZMuH_MqI0mRuS1N8zL3u-V34aAA2TVD7ZOTxJpt4-L9Oz9SFq_UZJpGEF5DlB9_hm0IGKOzEoiQ2FVjRLxv80HvHI-oNEAj2jn260BcuVz3lp2WOJOXmA"             },             "endpointId": "switch-000001"         },         "payload": {             "change": {                 "cause": {                     "type": "PHYSICAL_INTERACTION"                 },                 "properties": [                     {                         "namespace": "Alexa.ContactSensor",                         "name": "detectionState",                         "value": "NOT_DETECTED",                         "timeOfSample": "2023-11-11T14:38:17.522468611Z",                         "uncertaintyInMilliseconds": 0                     }                 ]             }         }     },     "context": {         "properties": [             {                 "namespace": "Alexa.EndpointHealth",                 "name": "connectivity",                 "value": {                     "value": "OK"                 },                 "timeOfSample": "2023-11-11T14:38:17.522468611Z",                 "uncertaintyInMilliseconds": 0             }         ]     } }
2023/11/11 14:38:17 Status response: 403 Forbidden
2023/11/11 14:38:17 Body response: {     "header": {         "namespace": "System",         "name": "Exception",         "messageId": "f5946669-cc39-461b-8c03-75c9c1380ae4"     },     "payload": {         "code": "SKILL_DISABLED_EXCEPTION",         "description": "The user does not have a valid enablement for your skill."     } }
2023/11/11 14:38:17 Handler ended: {     "Answer:": "Sensor_Motion_Kitchen" }
END RequestId: 189c76d4-9038-4137-aded-5ca8a75904a9

</body>
</html>

Thanks in advance

**Comment by Thundras** [comment] 2023-11-11 18:55
I just found the following in the amazon developer forum:

> Problem was that I assumed that us-west-2 (Oregon) is North America, whereas it represents "Far East". As a result, the 403 with a description of "The user does not have a valid enablement for your skill." actually means that asynchronous notifications are being sent to the wrong endpoint.
> 
> Solved the problem by sending async events to the "Far East" endpoint for users hitting the lambda function in us-west-2 with an AcceptGrant request
> 
> So if the user submits an accept grant in this region then the endpoint is as follows:
> 
> us-east-1 -> North America: https://api.amazonalexa.com/v3/events
> eu-west-1 -> Europe: https://api.eu.amazonalexa.com/v3/events
> us-west-2 -> Far East: https://api.fe.amazonalexa.com/v3/events

i have to register eu-west-1 myself, because i can't register the skill with us-east-1, because amazon probably checks what the nearest region is. so maybe you would have to make the event url definable via the database.

**Comment by Thundras** [comment] 2023-11-11 19:14
I changed the url in line 
`resp, err := http.Post("https://api.amazonalexa.com/v3/events", "application/json", bytes.NewBuffer(json)) `
in the push_update method to "https://api.eu.amazonalexa.com/v3/events", compiled and uploaded it and now my routines work.

maybe you can generalize the whole thing a bit so that not everyone has to recompile for their region.

**Comment by bmccluskey** [comment] 2023-11-11 21:04
@Thundras - you managed to find the same issue and developer article with the root cause as i did about 6 hours ago :)

Im in the UK and have configured the the Lambda and DynamoDB configured on eu-west-1.
I have successfully got the Skill added in the app, discovery has found and added my 3 switches. When I send state changes they reflect in the app but I think this is when Alexa makes the query back to Lambda routine. I think the push to Alexa isnt working correctly and routines are not being triggered.

I have spent the day trying a number of possible work arounds but without success. 

- I tried removing everything from eu-west-1 and installing again on us-east-1.  It will let me enable the skill, but wont find the devices.  
- Have even tried setting up a replicated DynamoDB between eu-west-1 and us-east-1. In the Smart Home page on the Alexa Developer put us-east-1 arn as the default and the eu-west-1 as the europe,india option. Allows me to join and discover the devices but getting the 401 errors. Also tried sending updates to apis in both locations.

Not sure how possible it is to the lambda function to detect where the function is running (eg us-east-1 or eu-west-1) and then choose the endpoint for sending based on that.

**Comment by Thundras** [comment] 2023-11-11 21:13
In the Incomming Request Json from the Gateway API there is a host section from which you can extract the region. Maybe that would be a possibility

**Comment by sweharris** [comment] 2023-11-11 21:25
Hmm.  I wasn't able to test in other regions (I'm in New Jersey so us-east-1).  I noted in the install readme that I wasn't sure where other regions should deploy to.

It's nice to know Alexa is just as messed up as AWS in general when it comes to regions!

I think a fix for this might be to document the three deployment areas, as per https://developer.amazon.com/en-GB/docs/alexa/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html#select-the-optimal-region-for-your-aws-lambda-function

```
NA | us-east-1 | US East (N. Virginia)
EU or IN | eu-west-1 | EU (Ireland)
FE | us-west-2 | US West (Oregon)
```

According to https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime  there's a runtime environment  variable which says what region we're running in.  I'll see if I can use that to select the right endpoint.  If I can't then I'll just define a new dummy button where an endpoint can be defined (maybe I'll allow that override, anyway).

Thanks for the detective work; I doubt I'd ever have found it myself!

**Comment by Thundras** [comment] 2023-11-11 21:30
i'll be happy when the project is up and running. then i can finally build my own motion detectors and door sensors without having to use the overpriced ones from hue or homematic. i'm happy to invest time in research to help you.

**Comment by sweharris** [comment] 2023-11-11 22:29
OK, so updates have been pushed.  It will automatically detect the region and if you deploy to one of  the 3 standard regions it should(!) pick the right endpoint automatically.

There's two new lines in the log when a notification is sent; e.g.
```
2023/11/11 22:23:27 Running in region: us-east-1
2023/11/11 22:23:27 Using API endpoint: https://api.amazonalexa.com/v3/events
2023/11/11 22:23:27 Status response: 202 Accepted
```

The install doc also has a new section: https://github.com/sweharris/Alexa-Smart-Home-VirtualButtons/tree/main/install#api-regional-endpoints which describes how to override these values if deployed to a different region.

**Comment by bmccluskey** [comment] 2023-11-11 23:28
That seems to work perfectly. Thank you so much!!
Detected my eu region, selected the eu endpoint and I got the 202 accepted.  Best of all the routine in Alexa picked it up and worked.

**Comment by Thundras** [comment] 2023-11-12 11:11
I can also confirm that everything is now working and the correct region is selected. Thank you very much.

**Comment by sweharris** [comment] 2023-11-12 11:56
Excellent.  Thank you both for your help!

**Closed by sweharris** 2023-11-12 11:56 UTC
