### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by sebcbien37** [sweharris/Alexa-Smart-Home-VirtualButtons#2] opened 2022-09-02 12:23 UTC
Hi ! 

Thanks for your project ! 

Everithing is working until "Add the skill to your Alexa".

**The error is (CloudWatch) :**
2022/09/01 19:42:53 &{400 Bad Request 400 HTTP/1.1 1 1 map[Cache-Control:[no-cache, no-store, must-revalidate] Connection:[keep-alive] Content-Length:[97] Content-Type:[application/json;charset=UTF-8] Date:[Thu, 01 Sep 2022 19:42:53 GMT] Permissions-Policy:[interest-cohort=()] Pragma:[no-cache] Server:[Server] Strict-Transport-Security:[max-age=47474747; includeSubDomains; preload] Vary:[Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent] X-Amz-Date:[Thu, 01 Sep 2022 19:42:53 GMT] X-Amz-Rid:[JX8J4ZBFDB0BHHAEFEJM] X-Amzn-Errortype:[OA2InvalidGrantException:http://internal.amazon.com/coral/com.amazon.panda/] X-Amzn-Requestid:[e7175a65-ef49-4310-9150-069851c0455e]] 0xc00007edc0 97 [] false false map[] 0xc0004f0000 0xc000306630}

I have seen in your code at "authorization_code", I have :
2022/09/01 19:42:53 map[client_id:[amzn1.application-oa2-client.cfb224dddddddddddddddd] client_secret:[e46453556727bddddddddddddddddddddd] code:[ANqTMeGcRlAIJLsdsss] grant_type:[authorization_code]]

But in the aws website I see that we need "code_verifier" and "redirect_uri".

Do you have the same problem ?

**Comment by sweharris** [comment] 2022-09-02 21:08
Hmm.  I wonder if you got one of the (many!) magic numbers wrong.

Obviously I haven't had to add this skill to my Alexa for 18 months; it's possible something has changed on the Amazon side of things.

If I get time this weekend I'll try and remove the skill from my Alexa, and re-add it (which should! cause it to generate a new token).

Typically "authorization_code" is used for automated workflows so should be the right thing here; redirect_uri flows are used for humans.  This is the workflow the code should be following; https://developer.amazon.com/en-US/docs/alexa/account-linking/configure-authorization-code-grant.html

Could you provide the log messages from before the failed call, so I can verify the path?

Early in my logs I see this:
```


START RequestId: 05719cb3-8243-4456-963c-3d61bbf710b5 Version: $LATEST
--
2021/04/21 01:12:14 Handler started
2021/04/21 01:12:14 Alexa call
2021/04/21 01:12:14
{
     "directive": {
         "header": {
             "namespace": "Alexa.Authorization",
             "name": "AcceptGrant",
             "messageId": "cb0edc91-3583-4848-8863-513772c47115",
             "payloadVersion": "3"
         },
         "payload": {
             "grant": {
                 "type": "OAuth2.AuthorizationCode",
                 "code": "XXXXX"
             },
             "grantee": {
                 "type": "BearerToken",
                 "token": "YYY"
             }
         }
     }
 }
2021/04/21 01:12:14 NameSpace: Alexa.Authorization, Name: AcceptGrant
```

We can see that's Alexa calling us and using the AuthorizanCode path (as expected).

We then continue:
```
2021/04/21 01:12:14 Attempting to get tokens for code: XXXXX
2021/04/21 01:12:14 200
2021/04/21 01:12:14 Body response: {     "access_token": "ZZZZ",     "token_type": "bearer",     "expires_in": 3600 }
2021/04/21 01:12:14 Result of Handler: {     "event": {         "header": {             "namespace": "Alexa.Authorization",             "name": "AcceptGrant.Response",             "messageId": "91432a95-a041-4e78-8cf8-dbaebb0f0478",             "payloadVersion": "3"         },         "payload": {}     } }
2021/04/21 01:12:14 Handler ended: {     "event": {         "header": {             "namespace": "Alexa.Authorization",             "name": "AcceptGrant.Response",             "messageId": "91432a95-a041-4e78-8cf8-dbaebb0f0478",             "payloadVersion": "3"         },         "payload": {}     } }
END RequestId: 05719cb3-8243-4456-963c-3d61bbf710b5
```

Which shows we succeeded.

**Comment by sebcbien37** [comment] 2022-09-03 12:18
Hi, I have :

`2022/09/01 19:42:52 {{{Alexa.Authorization AcceptGrant 50244e45-4c37-XXXXXXXXXX 3 } {{OAuth2.AuthorizationCode XXXXXXXXXXXXXXXXXXXX} {BearerToken Atza|IwEBIFib_vw6WOQZ57nxiDj3qjmuuLSsEaxhF5aHAOwXtTfoVOcfiF6DT6xWdbpcbFVQmOySJJF0nYUiHKhBLeb_ieNyXyI6M94U0u4mMNSMb8Nn7iYq_a7JXGtJ2GAPMgN8g_zHO2hawLNiwKZpce06e6gfkuilVWZH4dDqqc3DZMfSHDhF6qt64lSMbovXlsvnYqaVjIeuxyck6pOggXc3LQ6wV5TbRiBCnOEVMEHaSd858TuYPbwIVyuN1JmPANvE9b3TKlVbKlh57Lbl8rQ1eqlE6mhq5Ngt4uLACzf12b5qH7mTpCO1mWCwy_eC7KOrwpKOQiiuMUINkl-403POT1_pw76ohIew-jGRSlReKFSKbWyiVNgeTnKcLOWCJcH6KsThN42g9asvGdH_DmKYbsul}}}}`

`2022/09/01 19:42:53 map[client_id:[amzn1.application-oa2-client.cfb2243b2XXXXXXXXXX] client_secret:[e46453556727b54f89df22XXXXXXXXXXXXXXXXXXXX] code:[XXXXXXXXXX] grant_type:[authorization_code]]
`

`2022/09/01 19:42:53 &{400 Bad Request 400 HTTP/1.1 1 1 map[Cache-Control:[no-cache, no-store, must-revalidate] Connection:[keep-alive] Content-Length:[97] Content-Type:[application/json;charset=UTF-8] Date:[Thu, 01 Sep 2022 19:42:53 GMT] Permissions-Policy:[interest-cohort=()] Pragma:[no-cache] Server:[Server] Strict-Transport-Security:[max-age=47474747; includeSubDomains; preload] Vary:[Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent] X-Amz-Date:[Thu, 01 Sep 2022 19:42:53 GMT] X-Amz-Rid:[JX8J4ZBFDB0BHHAEFEJM] X-Amzn-Errortype:[OA2InvalidGrantException:http://internal.amazon.com/coral/com.amazon.panda/] X-Amzn-Requestid:[e7175a65-ef49-4310-9150-069851c0455e]] 0xc00007edc0 97 [] false false map[] 0xc0004f0000 0xc000306630}
`

`2022/09/01 19:42:53 Result of Handler: {
    "event": {
        "header": {
            "namespace": "Alexa.Authorization",
            "name": "ErrorResponse",
            "messageId": "a437efe3-c68f-4b78-97a3-aa5331a68d3a",
            "payloadVersion": "3"
        },
        "payload": {
            "type": "ACCEPT_GRANT_FAILED",
            "message": "We failed to get a token"
        }
    }
}
`

**Comment by sweharris** [comment] 2022-09-03 13:40
Hmm, it looks like the skill is sending the right message, and you have the client_id and client_secret set, which is good.

What region did you deploy in?  I only tested in us-east-1 but I don't _think_ this should make any difference.

I'll see if I have time this weekend to remove the skill from my Alexa and then re-add it, just in case the process has changed (but it doesn't look like it).   (unfortunately I got my 2nd shingles vaccine yesterday and I'm feeling a little brain-dead today; they say the side effects should pass in a day or two!).


However you should definitely check you followed all the install steps; there's a lot of them and it might be easy to miss one.  For example, if the "account linking" wasn't completed properly or if the "redirect urls" weren't set on the LWA profile then the request to convert the authorization code into a token would fail, similar to what you're seeing.

**Comment by sebcbien37** [comment] 2022-09-05 13:52
Your Access Token URI : https://api.amazon.com/auth/o2/token

On [https://stackoverflow.com/questions/48667128/what-is-the-correct-access-token-uri-for-aws-cognito-and-alexa-account-linking](https://stackoverflow.com/questions/48667128/what-is-the-correct-access-token-uri-for-aws-cognito-and-alexa-account-linking) I find : **Access Token URI: https://[your-cognito-domain].auth.us-east-1.amazoncognito.com/oauth2/token?state=[same-string-as-the-one-in-auth-url]**

I thing I can put :
[https://aws.auth.ue-west-1.amazoncognito.com/oauth2/token](https://aws.auth.ue-west-1.amazoncognito.com/oauth2/token)

**Comment by sweharris** [comment] 2022-09-06 00:15
Cognito is if you wanted to do your own authentication service; we're using LWA (login with amazon), so the URI I use is the right one.

FWIW, if you want to know the documentation I followed...
* The "basic" setup follows the official Alexa tutorial at https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes which refers to https://developer.amazon.com/en-US/docs/alexa/smarthome/steps-to-build-a-smart-home-skill.html
* The account linking details are at https://developer.amazon.com/en-US/docs/alexa/smarthome/set-up-account-linking-tutorial.html

OK... so I just created a brand new amazon test account and a brand new aws account and on a test phone added alexa to it with this.  So this is a clean from scratch setup.  And I followed my instructions.   Hmm, Amazon have changed the GUI somewhat, and it's now easier to setup a URL ("add a function URL" rather than setting up an API gateway.  I might rewrite the instructions to match these changes).

But it still works.  In particular, https://api.amazon.com/auth/o2/token is the correct URL.

```
2022/09/05 23:58:29 Alexa call
--
2022/09/05 23:58:29 
{
     "directive": {
         "header": {
             "namespace": "Alexa.Authorization",
             "name": "AcceptGrant",
             "messageId": "9a1a1516-708f-4e7f-bab5-5e0aa658322e",
             "payloadVersion": "3"
         },
         "payload": {
             "grant": {
                 "type": "OAuth2.AuthorizationCode",
                 "code": "XXX"
             },
             "grantee": {
                 "type": "BearerToken",
                 "token": "YYYY"
             }
         }
     }
 }
2022/09/05 23:58:29 NameSpace: Alexa.Authorization, Name: AcceptGrant
2022/09/05 23:58:30 Attempting to get tokens for code:XXXX
2022/09/05 23:58:30 200
2022/09/05 23:58:30 Body response: {     "access_token": "ZZZZ",     "refresh_token": "Z2",     "token_type": "bearer",     "expires_in": 3600 }
2022/09/05 23:58:30 Result of Handler: {     "event": {         "header": {             "namespace": "Alexa.Authorization",             "name": "AcceptGrant.Response",             "messageId": "64b711ef-c997-4516-a23c-99a7e8054bc9",             "payloadVersion": "3"         },         "payload": {}     } }
2022/09/05 23:58:30 Handler ended: {     "event": {         "header": {             "namespace": "Alexa.Authorization",             "name": "AcceptGrant.Response",             "messageId": "64b711ef-c997-4516-a23c-99a7e8054bc9",             "payloadVersion": "3"         },         "payload": {}     } }
END RequestId: 62d39187-a87b-427c-a469-c8a90456012e
REPORT RequestId: 62d39187-a87b-427c-a469-c8a90456012e	Duration: 1412.00 ms	Billed Duration: 1412 ms	Memory Size: 128 MB	Max Memory Used: 46 MB	Init Duration: 130.97 ms
```

So I think the code and instructions are correct.

What region did you deploy this in?  I've only tested in us-east-2 but it _should_ work elsewhere.

Did you verify you have all your magic numbers correct?  I'm wondering if your LWA profile doesn't have the correct 3 redirect URLs.

Amazon don't make it easy; there's so many moving parts (Alexa, Lambda, LWA) that it's hard to do it right first time!  When I was building this it took me multiple attempts.

**Comment by sebcbien37** [comment] 2022-09-06 13:19
Hi, I put the following region : ue-west-1.
I don't put the French region because I have seen that the French version blocks somes functions.

If I put my region, when I put the "Default endpoint" I have :
The Lambda ARN arn:aws:lambda:eu-west-3:6045XXXX6:function:Smart_Home_Virtual_Buttons is not valid for any of the supported region

**Comment by Thundras** [comment] 2023-11-08 10:28
Sorry to dig up the old post again, but I have exactly the same problem as sebcbien37. 
What surprises me is that in your instructions you write that the secret is 64 characters long (4x 0123456789abcdef) but the actual secret is longer and starts with "amzn1.oa2-cs.v1.". I have tried both variants but have had no success. I also went through your instructions several times to make sure I hadn't forgotten anything. As you have noticed yourself, the UI has changed in the meantime, so I sometimes had to guess which setting might be meant. Has anyone found out what the problem is in the meantime?

**Comment by sebcbien37** [comment] 2023-11-08 10:50
I tested it recently, everything worked. I couldn't go to the end because my installation was in http and not https.

**Comment by sweharris** [comment] 2023-11-09 00:55
@Thundras OK, I just created a new setup.  Yes, it looks like all the secrets now have amzn1.oa2-cs.v1. in front of them.  This IS part of the secret and needs to be included in the value.

Heh, I skipped my own instructions and forgot to create buttons 100002 and 100003 but the cloudwatch log told me!

```


2023/11/09 00:37:35 Lambda started
--
START RequestId: 870e1c0b-7750-4cec-b87c-0fcc52e4f0ec Version: $LATEST
2023/11/09 00:37:35 Handler started
2023/11/09 00:37:35 Incoming data:  {     "directive": {         "header": {             "namespace": "Alexa.Authorization",             "name": "AcceptGrant",             "messageId": "XXX",             "payloadVersion": "3"         },         "payload": {             "grant": {                 "type": "OAuth2.AuthorizationCode",                 "code": "XXX"             },             "grantee": {                 "type": "BearerToken",                 "token": "XXX"             }         }     } }
2023/11/09 00:37:35 Alexa call
2023/11/09 00:37:35 NameSpace: Alexa.Authorization, Name: AcceptGrant
2023/11/09 00:37:36 Ensure you have setclientid and setclientsecret before enabling skill
2023/11/09 00:37:36 Result of Handler: {     "event": {         "header": {             "namespace": "Alexa.Authorization",             "name": "ErrorResponse",             "messageId": "XXX",             "payloadVersion": "3"         },         "payload": {             "type": "ACCEPT_GRANT_FAILED",             "message": "We failed to get a token"         }     } }
```

Once I set up those values then the skill was successfully loaded onto my test phone's alexa app

```


2023/11/09 00:43:15 Alexa call
--
2023/11/09 00:43:15 NameSpace: Alexa.Authorization, Name: AcceptGrant
2023/11/09 00:43:15 Attempting to get tokens for code: XXX
2023/11/09 00:43:15 200
2023/11/09 00:43:15 Body response: {     "access_token": "XXX",     "refresh_token": "XXX",     "token_type": "bearer",     "expires_in": 3600 }
2023/11/09 00:43:15 Result of Handler: {     "event": {         "header": {             "namespace": "Alexa.Authorization",             "name": "AcceptGrant.Response",             "messageId": "XXX",             "payloadVersion": "3"         },         "payload": {}     } }
```

And once I defined a test button then Alexa was able to discover it correctly.

**Comment by Thundras** [comment] 2023-11-09 06:34
Hi @sweharris and @sebcbien37, 

Thank you for your feedback. I have had a look at the code. And it looks like I'm getting the error in the "do_user_auth" function at this point:

```
resp, err := http.PostForm("https://api.amazon.com/auth/o2/token", request)

	if err != nil {
		log.Println("Error getting code: " + err.Error())
		return "", false
	}

	if resp.StatusCode != http.StatusOK {
		return "", false
	}

	log.Println(resp.StatusCode)
```

If I read the log correctly, it should jump out at "if resp.StatusCode != http.StatusOK". Unfortunately, the StatusCode is only logged afterwards. I am a programmer myself and can read the code, but I am not a Go programmer and have no idea how to compile it myself.

**Comment by sweharris** [comment] 2023-11-09 12:08
You're right, it's in the wrong place.  I've updated the git repo, if you want to deploy the latest zip file.

If you're on Unix (and maybe MacOS) then you just need to install GoLang for your distribution and there's a Makefile that does the build.  Essentially it runs the comand

`CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -trimpath -o bootstrap alexa.go handler.go api.go command_mode.go main.go alexa_structs.go dynamo.go alexa_auth.go`

If you're on windows then install GoLang, set those variables and  run the build command.

Then (optionally) `strip bootstrap` to make it smaller (probably will only work on Linux), then put `bootstrap` into a file `lamba.zip`.  (`make lambda.zip` on Unix).

Annoyingly we don't get a lot of useful information when errors happen; when I was first building this it took a lot of banging my head on the wall whenever there was an error, but with all the magic numbers exactly correct it does work.

**Comment by Thundras** [comment] 2023-11-09 12:11
@sweharris many thanks for the information and I will try it out straight away. I'll let you know as soon as I know something about the status code

**Comment by Thundras** [comment] 2023-11-09 12:20
I get the error 401, which means something like "There was an error authenticating the sender account". Based on the structure of the request structure, this should be the Alexa Client Id and the Alexa Client Secret, right? This information is loaded from the database, buttonid 100002 and 100003. Then I have no idea what the problem is.

**Comment by sweharris** [comment] 2023-11-09 12:32
So definitely check there's no hidden whitespace in the button definitions.  It's always possible to get that when cut'n'pasting.   Also validate the "Allowed Return URLs" are correct and that you didn't set an allowed origin (that  must be empty) in the LWA web profile.

**Comment by Thundras** [comment] 2023-11-09 12:43
I'm such a complete idiot. There really was a blank at the end of the secret. I have re-entered it 1000 times and not noticed it. Now it works as it should. I can't thank you enough for your help. You have done a brilliant job with this project.

**Comment by sweharris** [comment] 2023-11-09 13:19
Nice!

Maybe I should add code to strip out leading/trailing spaces from id/secret (`strings.TrimSpace()` does it, probably in `get_buttons()`) because this might be catching out other people.  But I'll close this now since both of you appear to have got this working.

**Closed by sweharris** 2023-11-09 13:19 UTC
